"""second migration

Revision ID: 286bea1ca704
Revises: 12e5a2c47fec
Create Date: 2025-10-22 21:02:03.385768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286bea1ca704'
down_revision: Union[str, Sequence[str], None] = '12e5a2c47fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_unique_constraint(None, 'phone_numbers', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='unique')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.alter_column('activities', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
